# Generated by Django 4.1.4 on 2022-12-30 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description_alter_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0002_pago_expiration_date_pago_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='servicio_v1',
        ),
        migrations.AlterField(
            model_name='pago',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
