# Generated by Django 4.1.4 on 2022-12-20 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagos', '0002_pagos_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos_caducados',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('montodemulta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='usuario_pago',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('monto', models.FloatField(default=0.0)),
                ('fechadepago', models.DateField()),
                ('fechadecaducidad', models.DateField()),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.servicios')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.AddField(
            model_name='pagos_caducados',
            name='pago_usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.usuario_pago'),
        ),
    ]
