# Generated by Django 4.1.4 on 2022-12-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_free_amount', models.FloatField(default=0.0)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
    ]
